#!/usr/bin/env python3
"""Copy the web app's translations for every web i18n key used by the PDA app.

The PDA must use the same wording as erp.webapp so operators recognise every screen.
Every `tr('<namespace>.<key>')` call in lib/ whose key exists in the web locale files
(erp.webapp/src/locale/{en-US,zh-CN,de-DE}.json) is exported to lib/core/web_locale.g.dart.
PDA-only texts use the `pda.` prefix and live in lib/core/i18n.dart.

Usage:  python3 tool/sync_web_locale.py [path/to/erp.webapp]
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/erp.webapp')
LANGS = {'en': 'en-US.json', 'zh': 'zh-CN.json', 'de': 'de-DE.json'}

locales = {}
for lang, fn in LANGS.items():
    with open(os.path.join(WEB, 'src', 'locale', fn), encoding='utf-8') as f:
        locales[lang] = json.load(f)


def lookup(d, key):
    cur = d
    for part in key.split('.'):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur if isinstance(cur, str) else None


used = set()
pattern = re.compile(r"(?<![A-Za-z0-9_])tr\(\s*'([a-zA-Z0-9_.]+)'")
for base, _, files in os.walk(os.path.join(ROOT, 'lib')):
    for fn in files:
        if fn.endswith('.dart') and not fn.endswith('.g.dart'):
            with open(os.path.join(base, fn), encoding='utf-8') as f:
                used.update(pattern.findall(f.read()))
# keys built at runtime
used.update(k for k in (os.environ.get('EXTRA_KEYS') or '').split(',') if k)

table = {}
for key in sorted(used):
    if key.startswith('pda.'):
        continue
    en = lookup(locales['en'], key)
    if en is None:
        continue
    table[key] = {lang: (lookup(locales[lang], key) or en) for lang in LANGS}


def dart_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n') + "'"


out = ['// GENERATED by tool/sync_web_locale.py from erp.webapp/src/locale - do not edit.',
       '// Same wording as the web app (en-US / zh-CN / de-DE).',
       '',
       'const Map<String, Map<String, String>> webLocale = {']
for key, row in table.items():
    out.append(f"  {dart_str(key)}: {{" + ', '.join(f"{dart_str(l)}: {dart_str(v)}" for l, v in row.items()) + '},')
out.append('};')
out.append('')
path = os.path.join(ROOT, 'lib', 'core', 'web_locale.g.dart')
with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(out))
print(f'{len(table)} web keys -> {os.path.relpath(path, ROOT)}')
